logstash:
  image: logstash:1.5
  command: logstash -f /logstash/conf/*.conf
  ports:
    - "7001:7001"
  volumes:
    - logstash:/logstash
  links:
    - elasticsearch

elasticsearch:
  image: elasticsearch:1.5
  volumes:
    - elasticsearch/data:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"

kibana:
  image: webwurst/kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
