logstash:
  image: logstash
  command: /logstash/run
  ports:
    - "7001:7001"
  volumes:
      - logstash:/logstash
  links:
    - elasticsearch

elasticsearch:
  image: elasticsearch:1.5
  volumes:
    - elasticsearch/data:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"

kibana:
  image: local/kibana
  command: /kibana/run
  ports:
    - "5601:5601"
  volumes:
      - kibana:/kibana    
  links:
    - elasticsearch
