logstash:
  build: logstash/
  # image: codeformuenster/dh_logstash
  ports:
    - "7001:7001"
  links:
    - elasticsearch

elasticsearch:
  build: elasticsearch/
  # image: codeformuenster/dh_elasticsearch
  # volumes:
  #   - elasticsearch/data:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"

kibana:
  image: kibana:4.1
  ports:
    - "5601:5601"
  links:
    - elasticsearch
